definitions:
  api.apiErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.apiResponse:
    properties:
      message:
        type: string
    type: object
  api.loginUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.loginUserResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
      refresh_token:
        type: string
      refresh_token_expires_at:
        type: string
      user:
        $ref: '#/definitions/api.userResponse'
    type: object
  api.userResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  models.Hall:
    properties:
      cols:
        items:
          type: integer
        type: array
      id:
        type: string
      name:
        type: string
      rows:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /halls:
    get:
      consumes:
      - application/json
      description: Get all the existing halls
      operationId: listHalls
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hall'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      security:
      - bearerAuth: []
      summary: List existing halls
    post:
      consumes:
      - application/json
      description: Insert new hall
      operationId: InsertHall
      parameters:
      - description: Create hall
        in: body
        name: hall
        required: true
        schema:
          $ref: '#/definitions/models.Hall'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.Hall'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      security:
      - bearerAuth: []
      summary: Insert new hall
  /halls/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a single hall
      operationId: DeleteHall
      parameters:
      - description: Hall ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.apiResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      security:
      - bearerAuth: []
      summary: Delete a single hall
    put:
      consumes:
      - application/json
      description: Update a single hall
      operationId: UpdateHall
      parameters:
      - description: Hall ID
        in: path
        name: id
        required: true
        type: string
      - description: Update hall
        in: body
        name: hall
        required: true
        schema:
          $ref: '#/definitions/models.Hall'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hall'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      security:
      - bearerAuth: []
      summary: Update a single hall
  /halls/{name}:
    get:
      consumes:
      - application/json
      description: Get the existing halls
      operationId: searchHall
      parameters:
      - description: Hall name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hall'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      security:
      - bearerAuth: []
      summary: List existing halls
  /users/login:
    post:
      description: Authenticates a user and provides a Paseto/JWT to Authorize API
        calls
      operationId: loginUser
      parameters:
      - description: User login request
        in: body
        name: loginUserRequest
        required: true
        schema:
          $ref: '#/definitions/api.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.apiErrorResponse'
      summary: Provides a JSON Web Token
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
